version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: contenedor_mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - prestashop-net

  prestashop:
    image: prestashop/prestashop
    container_name: contenedor_prestashop
    ports:
      - 8080:80
    environment:
      - DB_SERVER=contenedor_mysql
    networks:
      - prestashop-net

  phpmyadmin:
    image: phpmyadmin
    container_name: contenedor_myadmin
    restart: always
    ports:
      - 9200:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=contenedor_mysql
      - PMA_PORT=3308
    networks:
      - prestashop-net

networks:
  prestashop-net:
    driver: bridge